[package]
name = "djanho-orm"
authors = ["Pedro N <itiropedro@gmail.com>", "João Ricardo <jrzr432@gmail.com>", "Marco <marco@gmail.com>", "Leonardo <leo@gmail.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "The Djanho ORM. A (not) blazing fast Rust Object Relational Mapper."

[dependencies]
