[package]
name = "djanho-orm"
authors = ["Pedro N <itiropedro@gmail.com>", "João Ricardo <jrzr432@gmail.com>", "Marco Antônio <markito1611@gmail.com>", "Leonardo <04144985631.com@gmail.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "The Djanho ORM. A (not) blazing fast Rust Object Relational Mapper."

[dependencies]
djanho-macros = { path = "macros" }
djanho-core = { path = "core" }

[workspace]
members = ["core","macros"]